# script to identify exact match in first 5 nucleotides to Ion Torrent barcodes 1-96 in INPUT.fasta
# writes 96 fasta files prefixed "OUTPUT_BCxx"  

cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTAAGGTAAC' | sed 's/^.\{0,5\}CTAAGGTAAC//' > OUTPUT_BC01.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TAAGGAGAAC' | sed 's/^.\{0,5\}TAAGGAGAAC//' > OUTPUT_BC02.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}AAGAGGATTC' | sed 's/^.\{0,5\}AAGAGGATTC//' > OUTPUT_BC03.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TACCAAGATC' | sed 's/^.\{0,5\}TACCAAGATC//' > OUTPUT_BC04.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CAGAAGGAAC' | sed 's/^.\{0,5\}CAGAAGGAAC//' > OUTPUT_BC05.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTGCAAGTTC' | sed 's/^.\{0,5\}CTGCAAGTTC//' > OUTPUT_BC06.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCGTGATTC' | sed 's/^.\{0,5\}TTCGTGATTC//' > OUTPUT_BC07.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCCGATAAC' | sed 's/^.\{0,5\}TTCCGATAAC//' > OUTPUT_BC08.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TGAGCGGAAC' | sed 's/^.\{0,5\}TGAGCGGAAC//' > OUTPUT_BC09.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTGACCGAAC' | sed 's/^.\{0,5\}CTGACCGAAC//' > OUTPUT_BC10.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCTCGAATC' | sed 's/^.\{0,5\}TCCTCGAATC//' > OUTPUT_BC11.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TAGGTGGTTC' | sed 's/^.\{0,5\}TAGGTGGTTC//' > OUTPUT_BC12.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTAACGGAC' | sed 's/^.\{0,5\}TCTAACGGAC//' > OUTPUT_BC13.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTGGAGTGTC' | sed 's/^.\{0,5\}TTGGAGTGTC//' > OUTPUT_BC14.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTAGAGGTC' | sed 's/^.\{0,5\}TCTAGAGGTC//' > OUTPUT_BC15.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTGGATGAC' | sed 's/^.\{0,5\}TCTGGATGAC//' > OUTPUT_BC16.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTATTCGTC' | sed 's/^.\{0,5\}TCTATTCGTC//' > OUTPUT_BC17.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}AGGCAATTGC' | sed 's/^.\{0,5\}AGGCAATTGC//' > OUTPUT_BC18.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTAGTCGGAC' | sed 's/^.\{0,5\}TTAGTCGGAC//' > OUTPUT_BC19.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CAGATCCATC' | sed 's/^.\{0,5\}CAGATCCATC//' > OUTPUT_BC20.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCGCAATTAC' | sed 's/^.\{0,5\}TCGCAATTAC//' > OUTPUT_BC21.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCGAGACGC' | sed 's/^.\{0,5\}TTCGAGACGC//' > OUTPUT_BC22.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TGCCACGAAC' | sed 's/^.\{0,5\}TGCCACGAAC//' > OUTPUT_BC23.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}AACCTCATTC' | sed 's/^.\{0,5\}AACCTCATTC//' > OUTPUT_BC24.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCTGAGATAC' | sed 's/^.\{0,5\}CCTGAGATAC//' > OUTPUT_BC25.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTACAACCTC' | sed 's/^.\{0,5\}TTACAACCTC//' > OUTPUT_BC26.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}AACCATCCGC' | sed 's/^.\{0,5\}AACCATCCGC//' > OUTPUT_BC27.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}ATCCGGAATC' | sed 's/^.\{0,5\}ATCCGGAATC//' > OUTPUT_BC28.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCGACCACTC' | sed 's/^.\{0,5\}TCGACCACTC//' > OUTPUT_BC29.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGAGGTTATC' | sed 's/^.\{0,5\}CGAGGTTATC//' > OUTPUT_BC30.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCAAGCTGC' | sed 's/^.\{0,5\}TCCAAGCTGC//' > OUTPUT_BC31.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTTACACAC' | sed 's/^.\{0,5\}TCTTACACAC//' > OUTPUT_BC32.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCTCATTGAAC' | sed 's/^.\{0,5\}TTCTCATTGAAC//' > OUTPUT_BC33.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCGCATCGTTC' | sed 's/^.\{0,5\}TCGCATCGTTC//' > OUTPUT_BC34.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TAAGCCATTGTC' | sed 's/^.\{0,5\}TAAGCCATTGTC//' > OUTPUT_BC35.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}AAGGAATCGTC' | sed 's/^.\{0,5\}AAGGAATCGTC//' > OUTPUT_BC36.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTTGAGAATGTC' | sed 's/^.\{0,5\}CTTGAGAATGTC//' > OUTPUT_BC37.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TGGAGGACGGAC' | sed 's/^.\{0,5\}TGGAGGACGGAC//' > OUTPUT_BC38.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TAACAATCGGC' | sed 's/^.\{0,5\}TAACAATCGGC//' > OUTPUT_BC39.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTGACATAATC' | sed 's/^.\{0,5\}CTGACATAATC//' > OUTPUT_BC40.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCCACTTCGC' | sed 's/^.\{0,5\}TTCCACTTCGC//' > OUTPUT_BC41.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}AGCACGAATC' | sed 's/^.\{0,5\}AGCACGAATC//' > OUTPUT_BC42.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTTGACACCGC' | ssed 's/^.\{0,5\}CTTGACACCGC//' > OUTPUT_BC43.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTGGAGGCCAGC' | sed 's/^.\{0,5\}TTGGAGGCCAGC//' > OUTPUT_BC44.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TGGAGCTTCCTC' | sed 's/^.\{0,5\}TGGAGCTTCCTC//' > OUTPUT_BC45.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCAGTCCGAAC' | sed 's/^.\{0,5\}TCAGTCCGAAC//' > OUTPUT_BC46.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TAAGGCAACCAC' | sed 's/^.\{0,5\}TAAGGCAACCAC//' > OUTPUT_BC47.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCTAAGAGAC' | sed 's/^.\{0,5\}TTCTAAGAGAC//' > OUTPUT_BC48.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCTAACATAAC' | ssed 's/^.\{0,5\}TCCTAACATAAC//' > OUTPUT_BC49.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGGACAATGGC' | sed 's/^.\{0,5\}CGGACAATGGC//' > OUTPUT_BC50.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTGAGCCTATTC' | sed 's/^.\{0,5\}TTGAGCCTATTC//' > OUTPUT_BC51.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCGCATGGAAC' | sed 's/^.\{0,5\}CCGCATGGAAC//' > OUTPUT_BC52.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTGGCAATCCTC' | sed 's/^.\{0,5\}CTGGCAATCCTC//' > OUTPUT_BC53.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCGGAGAATCGC' | sed 's/^.\{0,5\}CCGGAGAATCGC//' > OUTPUT_BC54.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCACCTCCTC' | sed 's/^.\{0,5\}TCCACCTCCTC//' > OUTPUT_BC55.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CAGCATTAATTC' | sed 's/^.\{0,5\}CAGCATTAATTC//' > OUTPUT_BC56.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTGGCAACGGC' | sed 's/^.\{0,5\}TCTGGCAACGGC//' > OUTPUT_BC57.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCTAGAACAC' | sed 's/^.\{0,5\}TCCTAGAACAC//' > OUTPUT_BC58.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCTTGATGTTC' | sed 's/^.\{0,5\}TCCTTGATGTTC//' > OUTPUT_BC59.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTAGCTCTTC' | sed 's/^.\{0,5\}TCTAGCTCTTC//' > OUTPUT_BC60.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCACTCGGATC' | sed 's/^.\{0,5\}TCACTCGGATC//' > OUTPUT_BC61.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCCTGCTTCAC' | sed 's/^.\{0,5\}TTCCTGCTTCAC//' > OUTPUT_BC62.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCTTAGAGTTC' | sed 's/^.\{0,5\}CCTTAGAGTTC//' > OUTPUT_BC63.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTGAGTTCCGAC' | sed 's/^.\{0,5\}CTGAGTTCCGAC//' > OUTPUT_BC64.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCTGGCACATC' | sed 's/^.\{0,5\}TCCTGGCACATC//' > OUTPUT_BC65.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCGCAATCATC' | sed 's/^.\{0,5\}CCGCAATCATC//' > OUTPUT_BC66.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCCTACCAGTC' | sed 's/^.\{0,5\}TTCCTACCAGTC//' > OUTPUT_BC67.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCAAGAAGTTC' | sed 's/^.\{0,5\}TCAAGAAGTTC//' > OUTPUT_BC68.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTCAATTGGC' | sed 's/^.\{0,5\}TTCAATTGGC//' > OUTPUT_BC69.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCTACTGGTC' | sed 's/^.\{0,5\}CCTACTGGTC//' > OUTPUT_BC70.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TGAGGCTCCGAC' | sed 's/^.\{0,5\}TGAGGCTCCGAC//' > OUTPUT_BC71.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGAAGGCCACAC' | sed 's/^.\{0,5\}CGAAGGCCACAC//' > OUTPUT_BC72.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCTGCCTGTC' | sed 's/^.\{0,5\}TCTGCCTGTC//' > OUTPUT_BC73.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGATCGGTTC' | sed 's/^.\{0,5\}CGATCGGTTC//' > OUTPUT_BC74.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCAGGAATAC' | sed 's/^.\{0,5\}CAGGAATAC//' > OUTPUT_BC75.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGGAAGAACCTC' | sed 's/^.\{0,5\}CGGAAGAACCTC//' > OUTPUT_BC76.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGAAGCGATTC' | sed 's/^.\{0,5\}CGAAGCGATTC//' > OUTPUT_BC77.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CAGCCAATTCTC' | sed 's/^.\{0,5\}CAGCCAATTCTC//' > OUTPUT_BC78.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCTGGTTGTC' | sed 's/^.\{0,5\}CCTGGTTGTC//' > OUTPUT_BC79.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCGAAGGCAGGC' | sed 's/^.\{0,5\}TCGAAGGCAGGC//' > OUTPUT_BC80.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCTGCCATTCGC' | sed 's/^.\{0,5\}CCTGCCATTCGC//' > OUTPUT_BC81.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTGGCATCTC' | sed 's/^.\{0,5\}TTGGCATCTC//' > OUTPUT_BC82.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTAGGACATTC' | sed 's/^.\{0,5\}CTAGGACATTC//' > OUTPUT_BC83.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTTCCATAAC' | sed 's/^.\{0,5\}CTTCCATAAC//' > OUTPUT_BC84.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCAGCCTCAAC' | sed 's/^.\{0,5\}CCAGCCTCAAC//' > OUTPUT_BC85.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTTGGTTATTC' | sed 's/^.\{0,5\}CTTGGTTATTC//' > OUTPUT_BC86.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTGGCTGGAC' | sed 's/^.\{0,5\}TTGGCTGGAC//' > OUTPUT_BC87.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CCGAACACTTC' | sed 's/^.\{0,5\}CCGAACACTTC//' > OUTPUT_BC88.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCTGAATCTC' | sed 's/^.\{0,5\}TCCTGAATCTC//' > OUTPUT_BC89.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTAACCACGGC' | sed 's/^.\{0,5\}CTAACCACGGC//' > OUTPUT_BC90.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGGAAGGATGC' | sed 's/^.\{0,5\}CGGAAGGATGC//' > OUTPUT_BC91.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTAGGAACCGC' | sed 's/^.\{0,5\}CTAGGAACCGC//' > OUTPUT_BC92.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CTTGTCCAATC' | sed 's/^.\{0,5\}CTTGTCCAATC//' > OUTPUT_BC93.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TCCGACAAGC' | sed 's/^.\{0,5\}TCCGACAAGC//' > OUTPUT_BC94.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}CGGACAGATC' | sed 's/^.\{0,5\}CGGACAGATC//' > OUTPUT_BC95.fasta
cat INPUT.fasta | grep --no-group-separator -E -B 1 '^.{0,5}TTAAGCGGTC' | sed 's/^.\{0,5\}TTAAGCGGTC//' > OUTPUT_BC96.fasta
